# Generated by Django 3.2.12 on 2023-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='BloodGlucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='HbConcentration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='MovementData',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='Platelets',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='RBC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='SleepMonitoring',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='WBC',
            field=models.FloatField(),
        ),
    ]
