# Generated by Django 3.1.5 on 2023-10-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231004_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='image',
            field=models.ImageField(default="% static {'img/profile_default_img.jpg'} %", upload_to='images/'),
        ),
    ]
