# Generated by Django 3.1.5 on 2024-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231006_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='signinuser',
            name='password',
        ),
        migrations.AddField(
            model_name='signinuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='signinuser',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
