# Generated by Django 3.1.5 on 2024-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240205_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
