# Generated by Django 3.1.5 on 2024-02-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_signinuser_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
