# Generated by Django 3.1.5 on 2024-02-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240205_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionmodel',
            name='calcium',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='calories_per_kg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='carbohydrates',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='fat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='fiber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='iron',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='minerals',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='protein',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='vitamin_d_iu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutritionmodel',
            name='water_consumption',
            field=models.CharField(max_length=50),
        ),
    ]
